// Reading the whole prep pack back and saying what's wrong with it.
//
// Everything else in Meeting Prep writes. This reads. The gap it fills: a
// brief can be completely up to date — nothing stale, nothing missing, every
// box generated by the current engine — and still be in the wrong order, open
// on the wrong thing, ask the same question three times, or spend its best
// section on the part of the meeting that matters least. Nothing in the app
// could ever say so, because every other action starts from "what should this
// box say" rather than "is this pack any good".
//
// The output is advice, not an edit. Each note carries a `fix` written as an
// instruction, so the writer can hand it straight back to be done for them,
// do it themselves and cross it off, or decide it's wrong and bin it.

import { anthropic, WRITER_MODEL } from "@/lib/anthropic";
import { SEAT_RULE, meetingContext, type MeetingPayload } from "./briefAi";

export interface WrittenNote {
  title: string;
  detail: string;
  target: string;
  targetLabel: string;
  fix: string;
  severity: "high" | "medium" | "low";
}

const REVIEW_SCHEMA = {
  type: "object" as const,
  properties: {
    notes: {
      type: "array" as const,
      items: {
        type: "object" as const,
        properties: {
          title: { type: "string" as const },
          detail: { type: "string" as const },
          target: { type: "string" as const },
          targetLabel: { type: "string" as const },
          fix: { type: "string" as const },
          severity: { type: "string" as const, enum: ["high", "medium", "low"] },
        },
        required: ["title", "detail", "target", "targetLabel", "fix", "severity"],
        additionalProperties: false,
      },
    },
  },
  required: ["notes"],
  additionalProperties: false,
};

function firstText(res: { content: { type: string; text?: string }[] }): string {
  const block = res.content.find((b) => b.type === "text");
  return (block?.text || "").trim();
}

export async function reviewPrep({
  meeting,
  kolBlock = "",
  briefText = "",
  questionsText = "",
  sectionKeys = [],
  research = "",
}: {
  meeting: MeetingPayload;
  kolBlock?: string;
  /** The brief as plain text, box by box, each headed by its key and title. */
  briefText?: string;
  /** The question bank as plain text, grouped. */
  questionsText?: string;
  /** The section keys that exist, so a note can target a real box. */
  sectionKeys?: string[];
  research?: string;
}): Promise<WrittenNote[]> {
  const context = [
    meetingContext(meeting, kolBlock),
    research && `The research this pack was built from:\n${research.slice(0, 12000)}`,
    briefText && `THE BRIEF AS IT STANDS:\n${briefText.slice(0, 24000)}`,
    questionsText && `THE QUESTION BANK AS IT STANDS:\n${questionsText.slice(0, 12000)}`,
  ]
    .filter(Boolean)
    .join("\n\n");

  const res = await anthropic().messages.create({
    model: WRITER_MODEL,
    max_tokens: 6000,
    output_config: { format: { type: "json_schema", schema: REVIEW_SCHEMA } },
    system: `You are the person the writer trusts to read their prep back to them the night before, and tell them the truth about it. You are not writing anything. You are finding what is wrong with what is already there.

${SEAT_RULE}

Read the whole pack as one thing, then give between 3 and 7 notes. Fewer is fine and better than padding. Rank them: the first note must be the one that would most change how the meeting goes.

What a good note is about:
- Order and emphasis. What they open on, what comes too late to matter, which section is doing the real work and is buried under one that isn't, what they should cut to make room.
- The gap. Something this meeting obviously needs that nothing in the pack covers, given the subject and who is in the room.
- The weak part. A section that is vague where it should be concrete, that gives direction without the words, that would read the same for any meeting in any industry, or that contradicts another section.
- Repetition. Three questions that are the same question, a point made in two boxes, a talking point that is already in the agenda.
- Risk. Something in here they would regret saying out loud: a claim that needs checking first, a number with no source, a line that assumes a fact nobody gave.
- What they will actually do in the room. Where the pack will fail them under pressure: no plan for the quiet person, nothing to say if the first question lands badly, no way back if they run short of time.

What a note is NEVER about:
- Praise. If a section is good, say nothing about it. There is no "strengths" note.
- Generic meeting advice ("listen actively", "build rapport", "be prepared"). If the note would be true of every meeting ever held, it is not a note.
- Formatting, length, tone, or the writing itself, unless it changes what happens in the room.
- Facts about these people or this meeting that the context does not give. Never invent a detail in order to have something to say. You may absolutely bring what you know about the SUBJECT.

Fields:
- title: the advice itself, as one short instruction the writer could act on. Start with a verb. Under 12 words. Not a question, not a heading.
- detail: one or two sentences on why it matters here and what good looks like. Concrete. Name the actual section, question or moment you mean.
- target: exactly one of — "section:<key>" using a key from the list of sections below, or "questions" for the question bank, or "setup" for something missing from what they told us, or "" when it is about the pack as a whole. Never invent a section key.
- targetLabel: how to say that target to a person ("Agenda", "Your questions", "Setup"). Two or three words.
- fix: the same advice rewritten as an instruction addressed to whoever will rewrite that section, specific enough to act on without the rest of this note. This gets handed over verbatim, so no "consider" and no "maybe" — say what to do.
- severity: "high" if the meeting goes materially worse without it, "medium" if it is a real improvement, "low" if it is a tidy-up.

Plain prose. No markdown, no bold, no emoji. Never an em dash or en dash.

The sections that exist, by key: ${sectionKeys.length ? sectionKeys.join(", ") : "(none yet)"}`,
    messages: [
      {
        role: "user",
        content: `${context || "(minimal context)"}\n\nRead it back and tell me what is wrong with it.`,
      },
    ],
  });
  if (res.stop_reason === "refusal") return [];

  const parsed = JSON.parse(firstText(res) || "{}");
  const allowed = new Set(sectionKeys.map((k) => `section:${k}`));
  const out: WrittenNote[] = [];
  for (const n of Array.isArray(parsed.notes) ? parsed.notes : []) {
    const title = String(n?.title || "").trim();
    const fix = String(n?.fix || "").trim();
    if (!title || !fix) continue;
    // A target the model made up would put a "Fix it" button on a box that
    // does not exist, so anything unrecognised falls back to whole-pack.
    const raw = String(n?.target || "").trim();
    const target =
      raw === "questions" || raw === "setup" || allowed.has(raw) ? raw : "";
    const severity = ["high", "medium", "low"].includes(String(n?.severity))
      ? (String(n.severity) as WrittenNote["severity"])
      : "medium";
    out.push({
      title,
      detail: String(n?.detail || "").trim(),
      target,
      targetLabel: String(n?.targetLabel || "").trim() || "This pack",
      fix,
      severity,
    });
  }
  return out;
}
